---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontEnd-deployment
  labels:
    app: frontEndapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontEndapp
  template:
    metadata:
      labels:
        app: frontEndapp
    spec:
      containers:
        - image: keoffor/project2-frontend:%TAG%
          imagePullPolicy: Always
          name: frondend-container
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendapi
  name: frontend-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: project-loader
      port: 8080
      targetPort: 8080
  selector:
    app: frontEndapp

